name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Check for build and type issues
    runs-on: ubuntu-latest

    env:
      SHARP_IGNORE_GLOBAL_LIBVIPS: "1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run check

      - name: Run Astro build
        run: npm run build